import { AuthProvider } from "../../../context/AuthContext";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <>  
    {/* <AuthProvider> */}
      <main>{children}</main> 
    {/* </AuthProvider> */}
    </>
  )


}
